apiVersion: apps/v1

kind: Deployment

metadata:
    name: chat-app-backend

spec:
    replicas: 2

    selector:
        matchLabels:
            app: web

    template:
        metadata:
            labels:
                app: web

        spec:
            containers:
                - name: chat-app-backend

                  image: europe-west2-docker.pkg.dev/chat-app-backend-1234/chat-app-backend/chat-app:v1

                  env:
                      - name: DATABASE_USER

                        valueFrom:
                            secretKeyRef:
                                name: chat-app-user

                                key: chat-app-user

                      - name: DATABASE_PASS

                        valueFrom:
                            secretKeyRef:
                                name: chat-app-pass

                                key: chat-app-pass

                      - name: DATABASE_HOST

                        valueFrom:
                            secretKeyRef:
                                name: chat-app-host

                                key: chat-app-host

                      - name: PORT

                        valueFrom:
                            secretKeyRef:
                                name: chat-app-port

                                key: chat-app-port

                      - name: SECRET

                        valueFrom:
                            secretKeyRef:
                                name: chat-app-session-secret

                                key: chat-app-session-secret
